{
 "title": "New dashboard",
 "time": { "from": "2023-02-22T05:42:46.000Z", "to": "2023-04-18T03:36:41.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  prediction_drift\nFROM dummy_metrics\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  share_missing_values\nFROM dummy_metrics\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  num_drifted_columns\nFROM dummy_metrics\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "50% Quantile Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", quantile_metric AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Conflict Prediction",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", share_not_stable_prediction AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}